export const items = [
  ['F001','Tumbler','dark grey insulated tumbler','LT2A','26 Aug 15:40',['grey','black','lid','500ml','metal'],['KL sticker underneath','small dent on right side']],
  ['F002','Mug','black ceramic coffee mug','Hive','26 Aug 11:15',['black','ceramic','mug','handle'],['chipped handle','gold star printed inside']],
  ['F003','Bottle','black Hydro Flask bottle','North Spine','27 Aug 14:20',['black','bottle','500ml','metal'],['blue sticker on base','scratch beside logo']],
  ['F004','Umbrella','black folding umbrella','NIE Library','25 Aug 17:30',['black','folding','umbrella'],['wooden handle','red thread near strap']],
  ['F005','Earbuds','white wireless earbuds in case','Canteen 2','26 Aug 13:15',['white','earbuds','wireless'],['green silicone case','right bud marked J']],
  ['F006','Tumbler','navy thermal cup with lid','North Spine','26 Aug 16:10',['navy','blue','lid','450ml'],['moon sticker underneath','silver straw']],
  ['F007','Thermos','black stainless-steel thermos','LT1A','26 Aug 15:10',['black','thermos','700ml','metal'],['name ALEX faintly engraved','dent near base']],
  ['F008','Wallet','brown leather card wallet','Business Library','28 Aug 10:05',['brown','wallet','leather'],['three transit cards','torn inner seam']],
  ['F009','Laptop','silver 13-inch laptop','Arc','27 Aug 18:40',['silver','laptop','13-inch'],['pixel-art sticker under case','small corner dent']],
  ['F010','Charger','white USB-C charger and cable','Lee Wee Nam Library','27 Aug 20:10',['white','charger','usb-c'],['initials MS on plug','frayed cable near tip']],
  ['F011','Bottle','transparent bottle with green cap','Hall 2','25 Aug 08:20',['clear','green','bottle','750ml'],['two measurement marks faded','leaf sticker']],
  ['F012','Bag','black canvas tote bag','Hive','29 Aug 12:30',['black','bag','canvas'],['orange notebook inside','stitched letter R']],
  ['F013','Card','student matriculation card','Canteen 1','29 Aug 13:40',['card','student','blue'],['surname starts with T','case has a crack']],
  ['F014','Keys','three keys on blue lanyard','North Spine','28 Aug 09:10',['keys','blue','lanyard'],['tiny bicycle charm','one brass key']],
  ['F015','Headphones','black over-ear headphones','Arc','26 Aug 19:30',['black','headphones','wireless'],['left cushion peeling','purple tape on band']],
  ['F016','Notebook','red A5 lined notebook','LT2A','27 Aug 10:25',['red','notebook','a5'],['first page has chemistry notes','coffee stain on back']],
  ['F017','Calculator','grey scientific calculator','SPMS','28 Aug 16:50',['grey','calculator'],['name label removed leaving mark','battery cover scratched']],
  ['F018','Watch','black digital sports watch','SRC','29 Aug 07:45',['black','watch','digital'],['strap hole stretched','alarm set to 06:30']],
  ['F019','Glasses','round black-frame glasses','Lee Wee Nam Library','25 Aug 22:00',['black','glasses','round'],['right arm slightly loose','blue hard case']],
  ['F020','Pouch','beige pencil pouch','NIE Library','27 Aug 15:00',['beige','pouch'],['cat keychain','green fountain pen inside']],
  ['F021','Mug','white ceramic mug','Canteen 2','28 Aug 09:35',['white','ceramic','mug','handle'],['hairline crack underneath','small red heart']],
  ['F022','Bottle','navy plastic sports bottle','SRC','26 Aug 18:05',['navy','blue','bottle','600ml'],['bite marks on nozzle','number 12 written below']],
  ['F023','Earbuds','black wireless earbuds','Hall 1','28 Aug 21:15',['black','earbuds','wireless'],['case hinge scratched','one medium ear tip missing']],
  ['F024','Cardholder','black fabric cardholder','North Spine','29 Aug 11:50',['black','card','fabric'],['yellow thread repair','photo tucked inside']],
  ['F025','Scarf','grey knitted scarf','Business Library','25 Aug 19:20',['grey','scarf','knitted'],['embroidered letter S','pulled thread at end']],
  ['F026','Mouse','white wireless mouse','Hive','29 Aug 17:10',['white','mouse','wireless'],['USB receiver stored inside','blue ink mark below']],
  ['F027','Cable','black USB-C cable','LT1A','28 Aug 14:00',['black','cable','usb-c'],['green tape near connector','1.5m length']],
  ['F028','Ring','silver ring','Canteen 1','27 Aug 12:45',['silver','ring'],['date engraved inside','tiny notch on edge']],
  ['F029','Jacket','navy zip-up jacket','Arc','25 Aug 16:30',['navy','blue','jacket'],['laundry tag marked 42','missing zipper pull']],
  ['F030','Book','blue statistics textbook','SPMS','29 Aug 14:35',['blue','book','textbook'],['notes on chapter 3','library receipt bookmark']]
].map(([id,type,description,location,foundAt,tags,hidden]) => ({id,type,description,location,foundAt,tags,hidden}));

export const publicItems = items.map(({hidden, ...publicItem}) => publicItem);
